# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'maincpp.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from side1 import *
from side2 import *

class maincpp(QtWidgets.QMainWindow):
    def __init__(self):
        super(maincpp,self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(601, 522)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 50, 411, 141))
        self.label.setObjectName("label")

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(230, 180, 171, 91))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 320, 171, 91))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton.raise_()
        self.label.raise_()
        self.pushButton_2.raise_()
        self.pushButton.clicked.connect(self.side)
        self.pushButton_2.clicked.connect(self.side_2)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">欢迎使用钢种代码查询系统</span></p></body></html>"))
        self.pushButton.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">输入钢种号查询成分</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "输入钢种号查询成分"))
        self.pushButton_2.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">输入钢种号查询成分</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Form", "输入成分查询钢种代号"))

    def side(self):
        ui_hello.show()
    #    Form.close()

    def side_2(self):
        ui_hello_2.show()
    #    Form.close()


if __name__ == "__main__":

    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = maincpp()
    ui_hello = side1()
    ui_hello_2 = side2()
    ui.setupUi(Form)
    
    Form.show()
    sys.exit(app.exec_())
